### ISSUE TITLE
login.gov: Help content for Open Opps + login.gov

### ISSUE THREAD

**Issue by sean-lewis** [openopps/OpenOppsTasks#75] opened 2018-07-31 13:43 UTC
**Old Trello URL:** https://trello.com/c/CvJuiUcx/316-logingov-help-content-for-open-opps-logingov

The following help center links will need to be updated for the login.gov release: 
1)  How to create an account - I think this is a separate card already just need to verify
https://usajobs.github.io/openopps-help/account/

**Comment by dalenard21** [comment] 2018-08-02 15:13
@minchung12 @kbwagner 

Is this issue to track all of the Open Opps help center content we need to update for the login.gov switch?

**Comment by dalenard21** [comment] 2018-08-07 12:07
Pages that need to be updated to talk about the new sign in process with login.gov:

- [ ] https://usajobs.github.io/openopps-help/account/

- [ ] https://usajobs.github.io/openopps-help/opportunity/ - consider about the step about creating an account. maybe talk more about having a profile, and having to create an account with login.gov, etc.

- [ ] https://usajobs.github.io/openopps-help/opportunity/participate/ - same comment as above

New  help content to create:

Do we need information about Open Opps and USAJOBS having one profile and one sign in process?

Do we want to point users to the USAJOBS help center and login.gov help center for questions about login.gov?  Otherwise we'll have repetitive content.

**Comment by kbwagner** [comment] 2018-08-08 23:46
@dalenard21 sorry still getting used to Github and just seeing this.  I just created a new card so I will close that once I can confirm they are all covered...the ones I hit were more related to where you got to see your status rather then login related things so it may be ok.

**Comment by dalenard21** [comment] 2018-08-15 17:43
@kbwagner @tlorrison @minchung12 

I have drafts of three pages in the Help Center that we need to update for the login.gov/profile changes.

How to create an account (or rather how to create a profile)
How to participate in an opportunity
How to create an opportunity

Please let me know if there are other pages that need to be updated.

[Open-opportunities-help-center-how-to-participate-opportunity-_20180815_v4.docx](https://github.com/openopps/openopps-design-team/files/2291140/Open-opportunities-help-center-how-to-participate-opportunity-_20180815_v4.docx)
[Open-opps-help-center-how-to-create-account_with_login_20180810_v3.docx](https://github.com/openopps/openopps-design-team/files/2291142/Open-opps-help-center-how-to-create-account_with_login_20180810_v3.docx)
[Open-opportunities-help-center-how-to-create-opportunity_20180808.docx](https://github.com/openopps/openopps-design-team/files/2291144/Open-opportunities-help-center-how-to-create-opportunity_20180808.docx)

**Comment by kbwagner** [comment] 2018-09-20 14:11
@lforeman can you please review? Then provide to Tracy for final approval.

**Comment by Lforeman22** [comment] 2018-09-21 16:13
@dalenard21 @tlorrison Looks good to me. My only question is, are we not going to address that you can also be a student to participate? Or are we waiting until Login work is approved to be released?

**Comment by dalenard21** [comment] 2018-09-26 15:35
@Lforeman22 that's a good question. I wasn't sure if 'students' were going out with the release?  I can update the 'How to participate' page to add in '...you must be a current federal employee or a current student'.  or something like that. I don't think we need to say anything on the create account page. And, I'm not sure about the how to create an opportunity page.

I was planning to update the 'What is open opportunities" content to include students, but when does that need to go out?

**Comment by dalenard21** [comment] 2019-02-08 18:55
@kbwagner Here are the updated pages in Federalist.  You might want to review one more time to make sure I have all the steps correct.  Otherwise This is ready for release.

https://federalist-proxy.app.cloud.gov/site/usajobs/openopps-help/account/

https://federalist-proxy.app.cloud.gov/site/usajobs/openopps-help/opportunity/

https://federalist-proxy.app.cloud.gov/site/usajobs/openopps-help/opportunity/participate/

**Comment by kbwagner** [comment] 2019-02-26 14:27
@dalenard21 I took a quick look and these look good.  The only thing I see is on this link: https://federalist-proxy.app.cloud.gov/site/usajobs/openopps-help/opportunity/participate/  the profile in OPen Opps will no longer have the bio section. The only thing we will have them do on Open Opps profile is add a picture and skills.
- we say a lot to apply to an opportunity you have to have a profile...I think it's ok for now but will somewhat be done for them once they have USAJOBS
- wondering if on the first link for creating account if we should say be sure you have a federal email address and agency filled in since those aren't required on the USAJOBS side but are on the Open Opps side.  
this is not looking like it will be going in the next release still due to waiting for the ATO for Open Opps.

**Comment by dalenard21** [comment] 2019-06-19 15:40
@kbwagner 

The Open Opps help center content has been updated in production:

https://usajobs.github.io/openopps-help/account/

https://usajobs.github.io/openopps-help/opportunity/

https://usajobs.github.io/openopps-help/opportunity/participate/

Closing issue.

**Closed by dalenard21** 2019-06-19 15:40 UTC
Labels: Content, Design, Waiting for release
